[build]
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200
